/**
 * Created by xiyuan on 16-5-11.
 */
apiUrlMapConfig(function ($app,$appConfig) {

    //数据接口配置
    $app.customConfig('apiUrlMap',{
        API_HOST:'paas.mecrmcrm.com',
         API_GATEWAY:'debug/afa4j',
        // API_GATEWAY:'afa4j',
        API_URL_MAP:{
            //创建字段
            'addModuleConfigField':'/custom/C01001',
            //模块配置管理查询字段分页
            'moduleConfigField':'/custom/C01002',
            //修改字段
            'editField':'/custom/C01003',
            //更新外键列
            'UpdateForeignKeyColumn':'/custom/C01004',
            //查询字段详情
            'getModuleConfigField':'/custom/C01005',
            //删除字段
            'deleteField':'/custom/C01006',
            //删除外键字段
            'deleteTheKeyFields':'/custom/C01007',
            //查询级联（外键）
            'queryCascadeForeign':'/custom/C01009',
            //查询模块字段及其关联模块字段的集合
            'queryModuleField':'/custom/C01010',
            //视图条件字段级联
            'viewConditionField':'/custom/C01013',
            //判断字段是否唯一
            'fieldIsUnique':'/custom/C01015',
            //查询视图包含字段集合
            'viewContainsFields':'/custom/C01016',
            //根据视图id获取视图查询字段
            'getViewQueryFields':'/custom/C01017',
            //根据模块id获取模块可筛选字段
            'getModulesFieldsByModuleID':'/custom/C01021',
            //查询字段是否被使用
            'QueryFieldIsUsed':'/custom/C01022',
            //模块配置管理视图操作分页
            'moduleConfigView':'/custom/C11001',
            //查询单个视图
            'querySingleView':'/custom/C11002',
            //添加视图
            'addModuleConfigView':'/custom/C11003',
            //删除特殊显示
            'deleteSpecialDisplay':'/custom/C11014',
            //删除视图
            'deleteView':'/custom/C11005',
            //更新视图
            'editModuleConfigView':'/custom/C11006',
            //查询视图集合
            'queryViewSet':'/custom/C11008',
            //查询可以批量新增的视图
            'viewsAddedBatches':'/custom/C11009',
            //查询视图的批量新增视图
            'batchQueryView':'/custom/C11010',
            //根据操作类型查找关联视图
            'relatedPages':'/custom/C11011',
            //根据操作类型查询目标视图
            'queryObjectView':'/custom/C11012',
            //添加视图特殊显示
            'addView':'/custom/C11015',
            //查询当前视图下的批量新增信息
            'QueryInformationCurrentView':'/custom/C11017',
            //模块配置管理查询操作分页
            'moduleConfigOperation':'/custom/C04005',
            //添加操作
            'addModuleConfigOperation':'/custom/C04001',
            //更新操作
            'editModuleConfigOperation':'/custom/C04003',
            //查询单个操作
            'getModuleConfigOperation':'/custom/C04004',
            //删除操作
            'deleteOperation':'/custom/C04002',
            //获取企业信息数据
            'getEnterpriseInformationData':'/org/O01001',
            //修改企业信息数据
            'editEnterpriseInformation':'/org/O01002',
            //获取首页标签数据
            'getHomeMark':'/auth/A01001',
            //创建首页标签
            'addHomeMark':'/auth/A01002',
            //更新首页标签
            'editHomeMark':'/auth/A01003',
            //删除首页标签
            'deleteHomeMark':'/auth/A01004',
            //查询首页标签分页
            'HomeMarkGridList':'/auth/A01005',
            //新增菜单
            'addMenu':'/auth/A05001',
            //更新菜单
            'editMenu':'/auth/A05002',
            //查询菜单集合
            'queryMenuList':'/auth/A05003',
            //查询单个菜单信息
            'getMenu':'/auth/A05004',
            //删除菜单
            'deleteMenu':'/auth/A05005',
            //查询菜单分页
            'menuGridList':'/auth/A05006',
            //新增用户服务
            'addOrganization':'/auth/A02001',
            //修改用户服务
            'editOrganization':'/auth/A02002',
            //查询用户详情服务
            'getOrganization':'/auth/A02003',
            //删除用户服务
            'deleteOrganization':'/auth/A02004',
            //重置用户密码服务
            'resetPasswordOrganization':'/auth/A02007',
            //修改用户密码服务
            'editPassword':'/auth/A02008',
            //判断用户账户是否唯一
            'accountIdUnique':'/auth/A02012',
            //查询角色集合
            'queryCharacterSet':'/auth/A03006',
            //模块数据迁移
            'moduleDataMigration':'/custom/C12007',
            //查询模块集合
            'queryModuleSet':'/custom/C10003',
            //新增组织架构
            'addOrganizational':'/org/O02001',
            //编辑组织架构
            'editOrganizationTree':'/org/O02002',
            //删除组织架构树
            'deleteOrganizationTree':'/org/O02003',
            //查询部门信息
            'queryOrganizational':'/org/O02004',
            //查询视图公式集合
            'queryViewFormulaSet':'custom/C02006',
            //查询模块下的查询标签
            'queryTagByModuleID':'custom/C08001',
            //查询字段约束集合
            'queryFieldConstraintSet':'custom/C13001',
            //查询视图分页
            'pageDisplayLabel':'custom/C11018',
            //====================================================================================================
            /*------模块信息------*/
            //查询模块集合(分页)
            'modulePage':'custom/C10002',
            //更新模块信息
            'editModule':'custom/C10005',
            //删除模块信息
            'deleteModule':'custom/C10006',
            //查询单个模块信息
            'moduleDetail':'custom/C10004',
            //新增模块
            'addModule':'custom/C10001',
            //模块编码唯一性校验
            'moduleCodeCheckout':'custom/C10008',
            //查询模块列表
            'moduleList':'custom/C10003',
            /*------视图公式配置页------*/
            //视图公式分页
            'viewFormulaList':'custom/C02001',
            //添加视图公式
            'addViewFormula':'custom/C02002',
            //更新视图公式
            'editViewFormula':'custom/C02003',
            //删除视图公式
            'deleteViewFormula':'custom/C02004',
            //查询当前模块下所有字段
            'moduleColumns':'custom/C01023',
            //查询单个视图公式详情
            'viewFormulaDetail':'custom/C02005',

            /*------系统字典页------*/
            //查询字典分页(子字典)
            'dictPagination':'base/B03010',
            //新增字典(单个--父字典)
            'addDict':'base/B03003',
            //批量新增字典(子字典)
            'addDictMultiple':'base/B03002',
            //更新字典
            'editDict':'base/B03004',
            //删除字典
            'deleteDict':'base/B03005',
            //查询字典详情
            'dictDetail': 'base/B03007',
            //查询字典集合(父字典)
            'dictionaryList':'base/B03008',
            //字典编码唯一性校验
            'dictCodeCheckout':'base/B03011',

            /*------视图条件配置------*/
            //查询视图树
            'viewTree':'custom/C11007',
            //查询视图条件分页
            'viewConditionsList':'custom/C07003',
            //新增视图条件
            'addViewConditions':'custom/C07004',
            //查询视图包含字段集合
            'viewColumns':'custom/C01016',
            //查询单个视图条件
            'viewConditionsDetail':'custom/C07002',
            //修改视图条件
            'editViewConditions':'custom/C07005',
            //删除视图条件
            'deleteViewConditions':'custom/C07001',
            //选择字段筛选时,要请求的--影响字段--接口
            'columnFilterAffectColumns':'custom/C01014',
            //选择字段筛选时,要请求的--字段--数据的接口
            'columnFilterCustomVal':'custom/C01020',

            /*------操作条件配置------*/
            //查询操作条件分页
            'operatConditionsList':'custom/C05002',
            //查询操作集合
            'viewOperations':'custom/C04006',
            //查询单个操作条件
            'operatConditionsDetail':'custom/C05003',
            //修改操作条件
            'editOperatConditions':'custom/C05005',
            //删除操作条件
            'deleteOperatConditions':'custom/C05004',
            //新增操作条件
            'addOperatConditions':'custom/C05001',

            /*------自定义权限------*/
            //查询自定义权限分页
            'customPermissionList':'auth/A07001',
            //查询自定义权限信息
            'customPermissionDetail':'auth/A07002',
            //修改自定义权限
            'editCustomPermission':'auth/A07004',
            //删除自定义权限
            'deleteCustomPermission':'auth/A07003',
            //新增自定义权限
            'addPermission':'auth/A07005',

            /*------通知公告(后台设置)----*/
            //查询单条公告明细
            'notifyDetail':'message/M03007',
            //更新通知公告
            'editNotify':'message/M03002',
            //删除通知公告
            'deleteNotify':'message/M03003',
            //查询组织架构树
            'orgTreeList':'org/O02006 ',
            //添加通知公告
            'addNotify':'message/M03001',
            //查询发送公告分页
            'sendNotifyList':'message/M03006',

            /*------角色权限------*/
            //查询所有角色
            'roleList':'auth/A03002',
            //新增角色
            'addRole':'auth/A03001',
            //角色明细
            'roleDetail':'auth/A03005',
            //修改角色
            'editRole':'auth/A03003',
            //删除角色
            'deleteRole':'auth/A03004',
            //获取权限列表
            'permissionList':'auth/A06004',
            //新增角色权限
            'addPermissionList':'auth/A04001',
            //权限克隆
            'cloneRolePermission':'auth/A04003',
            //角色授权多个用户
            'authorizeRole':'auth/A02006',
            //查询用户分页
            'userList':'auth/A02009',

            /*------消息模板------*/
            //查询消息模板分页
            'messageTempList':'message/M02005',
            //新增消息模板
            'addMessage':'message/M02001 ',
            //消息模板详情
            'detailMessage':'message/M02004 ',
            //修改消息模板
            'editMessage':'message/M02002 ',
            //删除消息模板
            'deleteMessage':'message/M02003 ',

            /*-------系统日志接口定义-------*/
            //后台配置日志列表
            'backStageConfigLogList':'log/L02002',
            'frontOperationLogList':'log/L01002',

            /*-------前台接口定义-------*/
            //菜单列表
            'menuList':'auth/A05007',
            //新增表单数据结构
            'addFormStruct':'render/R01001',
            //查询字典集合
            'queryMaps':'base/B03008',
            //组织架构集合
            'orgList':'org/O02006',
            //查询用户集合服务
            'userInfoList':'auth/A02005',
            //自定义grid结构
            'gridStructure':'custom/C12002',
            //视图渲染条件
            'viewRenderConditions':'render/R01003',
            //查询可搜索字段
            'viewCanSearch':'custom/C01011',

            //当前位置部分 获取当前视图的位置信息
            'currentLocation':'custom/C14003',
            //查询单个视图详情
            'viewSearchDetail':'custom/C11002',
            //列表操作中删除数据
            'viewOperationDelete':'custom/C12003',
            //查询系统标签
            'systemSearch':'custom/C08002',
            //详情视图渲染
            'detailViewRendering':'render/R01004',
            //查询首页标签集合
            'homePageSearch':'auth/A01006',
            //编辑页面数据渲染
            'editFormStruct':'render/R01002',
            //新增查询标签
            'queryTags':'custom/C08007',
            //删除查询标签
            'deleteTags':'custom/C08004',
            //查询自定义标签
            'customerSearch':'custom/C08005',

            //真实数据字段唯一性校验
            'realUnique':'custom/C12009',
            //真实数据详情页面子数据
            'babygridStructure':'custom/C12012',
            //新增真实数据
            'realAdd':'custom/C12004',
            //真实数据修改
            'realUpdate':'custom/C12005',

            //查询单个消息详情
            'singleNewsDetail':'message/M01006',
            //查询消息列表
            'messageList':'message/M01005',
            //查询消息总数服务
            'totalMessage':'message/M01004',
            //删除消息服务
            'deleteMessages':'message/M01003',
            //标记消息已读
            'readMessage':'message/M01002',

            /*前台菜单*/
            //查询快捷菜单集合
            'shortcutMenuList':'auth/A05009',
            //视图布局保存
            'viewLayoutSave':'custom/C11019'
        }
    });

});