
//查询字典集合
model('queryMaps',function () {

    var M = this,
        queryMapsServer = this.server({
            serverType: 'api',
            url: 'queryMaps'
        });

    this.method('getData', function (dictType,sendData) {
        queryMapsServer.success(function (res) {

            var dataList= [];

            res.forEach(function (info) {
                dataList.push({
                    content:info.dictName,
                    value:info.dictCode
                })
            });

            M.$model=dataList;

        }).fail(function (msg) {
            console.log(msg)
        }).send({dictType:dictType}.extend(sendData||{}));
    })

});

//组织架构集合 [tree的数据结构]
model('orgList',['$:@lib/custom/commApi/orgListConvert'],function ($orgListConvert) {
    var M = this;
        //orgListServer = this.server({
        //    serverType: 'api',
        //    url: 'orgList'
        //});

    this.method('getData', function (orgParentCode) {
        //orgListServer.success(function (res) {
        //    M.$model={
        //        list:$orgListConvert(res.organzationList)
        //    };
        //}).fail(function (msg) {
        //    console.log(msg)
        //}).send({orgParentCode:orgParentCode||0});

        var res={
            "tradeName": "查询组织机构树形数据格式集合",
            "data": {
                "organzationList": [
                    {
                        "orgName": "集团管理层",
                        "isDelete": 0,
                        "groupId": null,
                        "extCode": null,
                        "extParentCode": null,
                        "entCode": "TJ",
                        "createTime": 1469677084000,
                        "orgCode": "011",
                        "uUserCode": "ME_0001",
                        "operationType": "INSERT",
                        "id": 69,
                        "cUserCode": "ME_0001",
                        "orgDesc": "",
                        "orgParentCode": "0",
                        "groupCode": null,
                        "lastUpdateTime": 1469677084000
                    },
                    {
                        "orgName": "董事会",
                        "isDelete": 0,
                        "groupId": null,
                        "extCode": null,
                        "extParentCode": null,
                        "entCode": "TJ",
                        "createTime": 1469677144000,
                        "orgCode": "012",
                        "uUserCode": "ME_0001",
                        "operationType": "INSERT",
                        "id": 70,
                        "cUserCode": "ME_0001",
                        "orgDesc": "",
                        "orgParentCode": "0",
                        "groupCode": null,
                        "lastUpdateTime": 1469677144000
                    },
                    {
                        "orgName": "财务管理中心",
                        "isDelete": 0,
                        "groupId": null,
                        "extCode": null,
                        "extParentCode": null,
                        "entCode": "TJ",
                        "createTime": 1469677210000,
                        "orgCode": "014",
                        "uUserCode": "US000000137",
                        "operationType": "UPDATE",
                        "id": 72,
                        "cUserCode": "ME_0001",
                        "orgDesc": "测试",
                        "orgParentCode": "0",
                        "groupCode": null,
                        "lastUpdateTime": 1476153077000
                    },
                    {
                        "orgName": "IT管理部",
                        "isDelete": 0,
                        "groupId": null,
                        "extCode": null,
                        "extParentCode": null,
                        "entCode": "TJ",
                        "createTime": 1469677688000,
                        "orgCode": "019",
                        "uUserCode": "US000000137",
                        "operationType": "UPDATE",
                        "id": 77,
                        "cUserCode": "ME_0001",
                        "orgDesc": "IT管理部",
                        "orgParentCode": "0",
                        "groupCode": null,
                        "lastUpdateTime": 1476153199000
                    },
                    {
                        "orgName": "业务管理部",
                        "isDelete": 0,
                        "groupId": null,
                        "extCode": null,
                        "extParentCode": null,
                        "entCode": "TJ",
                        "createTime": 1470114556000,
                        "orgCode": "021",
                        "uUserCode": "US000000137",
                        "operationType": "UPDATE",
                        "id": 81,
                        "cUserCode": "ME_0001",
                        "orgDesc": "业务管理部",
                        "orgParentCode": "0",
                        "groupCode": null,
                        "lastUpdateTime": 1476153342000
                    },
                    {
                        "orgName": "SOHO直营",
                        "isDelete": 0,
                        "groupId": null,
                        "extCode": null,
                        "extParentCode": null,
                        "entCode": "TJ",
                        "createTime": 1470114604000,
                        "orgCode": "023",
                        "uUserCode": "US000000137",
                        "operationType": "UPDATE",
                        "id": 83,
                        "cUserCode": "ME_0001",
                        "orgDesc": "SOHO直营",
                        "orgParentCode": "0",
                        "groupCode": null,
                        "lastUpdateTime": 1476154809000
                    },
                    {
                        "orgName": "机构渠道部",
                        "isDelete": 0,
                        "groupId": null,
                        "extCode": null,
                        "extParentCode": null,
                        "entCode": "TJ",
                        "createTime": 1470114617000,
                        "orgCode": "024",
                        "uUserCode": "ME_0001",
                        "operationType": "INSERT",
                        "id": 84,
                        "cUserCode": "ME_0001",
                        "orgDesc": "",
                        "orgParentCode": "0",
                        "groupCode": null,
                        "lastUpdateTime": 1470114617000
                    },
                    {
                        "orgName": "机构一部",
                        "isDelete": 0,
                        "groupId": null,
                        "extCode": null,
                        "extParentCode": null,
                        "entCode": "TJ",
                        "createTime": 1476151883000,
                        "orgCode": "024001",
                        "uUserCode": "US000000137",
                        "operationType": "INSERT",
                        "id": 86,
                        "cUserCode": "US000000137",
                        "orgDesc": "",
                        "orgParentCode": "024",
                        "groupCode": null,
                        "lastUpdateTime": 1476151883000
                    },
                    {
                        "orgName": "机构二部",
                        "isDelete": 0,
                        "groupId": null,
                        "extCode": null,
                        "extParentCode": null,
                        "entCode": "TJ",
                        "createTime": 1476151900000,
                        "orgCode": "024002",
                        "uUserCode": "US000000137",
                        "operationType": "INSERT",
                        "id": 87,
                        "cUserCode": "US000000137",
                        "orgDesc": "",
                        "orgParentCode": "024",
                        "groupCode": null,
                        "lastUpdateTime": 1476151900000
                    },
                    {
                        "orgName": "财务部",
                        "isDelete": 0,
                        "groupId": null,
                        "extCode": null,
                        "extParentCode": null,
                        "entCode": "TJ",
                        "createTime": 1476152944000,
                        "orgCode": "014001",
                        "uUserCode": "US000000137",
                        "operationType": "INSERT",
                        "id": 88,
                        "cUserCode": "US000000137",
                        "orgDesc": "",
                        "orgParentCode": "014",
                        "groupCode": null,
                        "lastUpdateTime": 1476152944000
                    },
                    {
                        "orgName": "风控部",
                        "isDelete": 0,
                        "groupId": null,
                        "extCode": null,
                        "extParentCode": null,
                        "entCode": "TJ",
                        "createTime": 1476152957000,
                        "orgCode": "014002",
                        "uUserCode": "US000000137",
                        "operationType": "INSERT",
                        "id": 89,
                        "cUserCode": "US000000137",
                        "orgDesc": "",
                        "orgParentCode": "014",
                        "groupCode": null,
                        "lastUpdateTime": 1476152957000
                    },
                    {
                        "orgName": "法务部",
                        "isDelete": 0,
                        "groupId": null,
                        "extCode": null,
                        "extParentCode": null,
                        "entCode": "TJ",
                        "createTime": 1476152968000,
                        "orgCode": "014003",
                        "uUserCode": "US000000137",
                        "operationType": "INSERT",
                        "id": 90,
                        "cUserCode": "US000000137",
                        "orgDesc": "",
                        "orgParentCode": "014",
                        "groupCode": null,
                        "lastUpdateTime": 1476152968000
                    },
                    {
                        "orgName": "品牌公关中心",
                        "isDelete": 0,
                        "groupId": null,
                        "extCode": null,
                        "extParentCode": null,
                        "entCode": "TJ",
                        "createTime": 1476941816000,
                        "orgCode": "025",
                        "uUserCode": "ME_0001",
                        "operationType": "INSERT",
                        "id": 91,
                        "cUserCode": "ME_0001",
                        "orgDesc": "品牌公关中心",
                        "orgParentCode": "0",
                        "groupCode": null,
                        "lastUpdateTime": 1476941816000
                    },
                    {
                        "orgName": "品牌部",
                        "isDelete": 0,
                        "groupId": null,
                        "extCode": null,
                        "extParentCode": null,
                        "entCode": "TJ",
                        "createTime": 1476941836000,
                        "orgCode": "025001",
                        "uUserCode": "ME_0001",
                        "operationType": "INSERT",
                        "id": 92,
                        "cUserCode": "ME_0001",
                        "orgDesc": "品牌部",
                        "orgParentCode": "025",
                        "groupCode": null,
                        "lastUpdateTime": 1476941836000
                    },
                ]
            },
            "logFileName": "G1_org_O02006_64.log",
            "message": "操作成功",
            "uuid": "C86070C83B934E9DA1A386A6BC230359",
            "status": 200,
            "errorParams": null
        }

        M.$model={
            list:$orgListConvert(res.data.organzationList)
        };

    })
});

//查询用户集合服务  [数组结构 ,tree专用]
model('userInfoList',['$:@lib/custom/commApi/orgListConvert'],function ($orgListConvert) {
    var M = this;
    //    userInfoListServer = this.server({
    //        serverType: 'api',
    //        url: 'userInfoList'
    //    });
    //this.method('getData', function (orgCode) {
    //    userInfoListServer.onceSuccess(function (res) {
    //        M.$model=res;
    //    }).onceFail(function (msg) {
    //        console.log(msg)
    //    }).send({orgCode:orgCode||0});
    //})

    var res={
        "tradeName": "查询用户列表",
        "data": [
            {
                "superiorLeader": null,
                "userCode": null,
                "orgId": 70,
                "orgCode": "012",
                "uUserCode": "ME_0001",
                "id": 207,
                "email": "2134234@qq.com",
                "address": null,
                "isDelete": 0,
                "sex": 1,
                "mobile": "15755532342",
                "telephone": "15755532342",
                "userDesc": "",
                "isAdmin": 0,
                "qqId": "2134312423",
                "headPhoto": null,
                "accountId": "sdfasfs",
                "realName": "3425435",
                "roleIds": "21",
                "extCode": null,
                "shdEnable": 0,
                "pwValidDate": 33027533822000,
                "createTime": 1491533655000,
                "entCode": "TJ",
                "weiboId": "werwqerwq",
                "wechatId": "wqerewqrrw",
                "cUserCode": "ME_0001",
                "job": null,
                "status": null,
                "lastUpdateTime": 1491533655000
            },
            {
                "superiorLeader": null,
                "userCode": null,
                "orgId": 70,
                "orgCode": "012",
                "uUserCode": "ME_0001",
                "id": 206,
                "email": "12342234@qq.com",
                "address": null,
                "isDelete": 0,
                "sex": 1,
                "mobile": "15755352666",
                "telephone": "15755352666",
                "userDesc": "",
                "isAdmin": 0,
                "qqId": "123424234",
                "headPhoto": null,
                "accountId": "ewrtewter",
                "realName": "8888",
                "roleIds": "21",
                "extCode": null,
                "shdEnable": 0,
                "pwValidDate": null,
                "createTime": 1491533224000,
                "entCode": "TJ",
                "weiboId": "werwerwqr",
                "wechatId": "wqerewqrww",
                "cUserCode": "ME_0001",
                "job": null,
                "status": null,
                "lastUpdateTime": 1491533224000
            },
            {
                "superiorLeader": null,
                "userCode": null,
                "orgId": 70,
                "orgCode": "012",
                "uUserCode": "ME_0001",
                "id": 205,
                "email": "rewr@qq.com",
                "address": null,
                "isDelete": 0,
                "sex": 1,
                "mobile": "15735355353",
                "telephone": "15735355353",
                "userDesc": "",
                "isAdmin": 0,
                "qqId": "5432453434",
                "headPhoto": null,
                "accountId": "sgdsfgd",
                "realName": "xinzeng1",
                "roleIds": "20",
                "extCode": "15735355353",
                "shdEnable": 0,
                "pwValidDate": null,
                "createTime": 1491467364000,
                "entCode": "TJ",
                "weiboId": "rewtewrtt",
                "wechatId": "345rtetewrt",
                "cUserCode": "ME_0001",
                "job": null,
                "status": 0,
                "lastUpdateTime": 1491469508000
            },
            {
                "superiorLeader": 34,
                "userCode": "US000000154",
                "orgId": 81,
                "orgCode": "021",
                "uUserCode": "US000000137",
                "id": 204,
                "email": "",
                "address": "",
                "isDelete": 0,
                "sex": 1,
                "mobile": "13817968154",
                "telephone": "",
                "userDesc": "",
                "isAdmin": 1,
                "qqId": "",
                "headPhoto": null,
                "accountId": "13817968154",
                "realName": "陶慧",
                "roleIds": "19",
                "extCode": "",
                "shdEnable": 0,
                "pwValidDate": 33027423977000,
                "createTime": 1479285770000,
                "entCode": "TJ",
                "weiboId": "",
                "wechatId": "",
                "cUserCode": "US000000137",
                "job": null,
                "status": 1,
                "lastUpdateTime": 1479285770000
            },
            {
                "superiorLeader": null,
                "userCode": "US000000153",
                "orgId": 88,
                "orgCode": "014001",
                "uUserCode": "US000000137",
                "id": 202,
                "email": "",
                "address": "",
                "isDelete": 0,
                "sex": 0,
                "mobile": "15801798697",
                "telephone": "",
                "userDesc": "",
                "isAdmin": 0,
                "qqId": "",
                "headPhoto": null,
                "accountId": "15801798697",
                "realName": "石妮君",
                "roleIds": "33,36",
                "extCode": "",
                "shdEnable": 0,
                "pwValidDate": 33009137337000,
                "createTime": 1479278223000,
                "entCode": "TJ",
                "weiboId": "",
                "wechatId": "",
                "cUserCode": "ME_0001",
                "job": null,
                "status": 1,
                "lastUpdateTime": 1479284275000
            },
            {
                "superiorLeader": 16,
                "userCode": "US000000151",
                "orgId": 89,
                "orgCode": "014002",
                "uUserCode": "ME_0001",
                "id": 40,
                "email": "",
                "address": "",
                "isDelete": 0,
                "sex": 0,
                "mobile": "13062812706",
                "telephone": "",
                "userDesc": "",
                "isAdmin": 0,
                "qqId": "",
                "headPhoto": null,
                "accountId": "13062812706",
                "realName": "胡丽娟",
                "roleIds": "31,35,36,36,36",
                "extCode": "",
                "shdEnable": 0,
                "pwValidDate": 33009129617000,
                "createTime": 1477449094000,
                "entCode": "TJ",
                "weiboId": "",
                "wechatId": "",
                "cUserCode": "ME_0001",
                "job": null,
                "status": 1,
                "lastUpdateTime": 1477449934000
            },
            {
                "superiorLeader": null,
                "userCode": "US000000150",
                "orgId": 92,
                "orgCode": "025001",
                "uUserCode": "ME_0001",
                "id": 39,
                "email": "",
                "address": "",
                "isDelete": 0,
                "sex": 1,
                "mobile": "18918172735",
                "telephone": "",
                "userDesc": "",
                "isAdmin": 0,
                "qqId": "",
                "headPhoto": null,
                "accountId": "18918172735",
                "realName": "朱樱",
                "roleIds": "22",
                "extCode": "",
                "shdEnable": 0,
                "pwValidDate": 33009140338000,
                "createTime": 1476941907000,
                "entCode": "TJ",
                "weiboId": "",
                "wechatId": "",
                "cUserCode": "ME_0001",
                "job": null,
                "status": 1,
                "lastUpdateTime": 1476941907000
            },
            {
                "superiorLeader": 25,
                "userCode": "US000000149",
                "orgId": 83,
                "orgCode": "023",
                "uUserCode": "ME_0001",
                "id": 38,
                "email": "",
                "address": "",
                "isDelete": 0,
                "sex": 1,
                "mobile": "13818454979",
                "telephone": "",
                "userDesc": "",
                "isAdmin": 0,
                "qqId": "",
                "headPhoto": null,
                "accountId": "13818454979",
                "realName": "章迪",
                "roleIds": "20",
                "extCode": "",
                "shdEnable": 0,
                "pwValidDate": 33009144042000,
                "createTime": 1476770824000,
                "entCode": "TJ",
                "weiboId": "",
                "wechatId": "",
                "cUserCode": "ME_0001",
                "job": null,
                "status": 0,
                "lastUpdateTime": 1476941035000
            },
            {
                "superiorLeader": 25,
                "userCode": "US000000148",
                "orgId": 83,
                "orgCode": "023",
                "uUserCode": "ME_0001",
                "id": 37,
                "email": "",
                "address": "",
                "isDelete": 0,
                "sex": 0,
                "mobile": "18221431125",
                "telephone": "",
                "userDesc": "",
                "isAdmin": 0,
                "qqId": "",
                "headPhoto": null,
                "accountId": "18221431125",
                "realName": "周慧",
                "roleIds": "20",
                "extCode": "",
                "shdEnable": 0,
                "pwValidDate": 33009154178000,
                "createTime": 1476696550000,
                "entCode": "TJ",
                "weiboId": "",
                "wechatId": "",
                "cUserCode": "ME_0001",
                "job": null,
                "status": 0,
                "lastUpdateTime": 1476941026000
            },
            {
                "superiorLeader": 35,
                "userCode": "US000000146",
                "orgId": 86,
                "orgCode": "024001",
                "uUserCode": "ME_0001",
                "id": 35,
                "email": "",
                "address": "",
                "isDelete": 0,
                "sex": 1,
                "mobile": "13795225919",
                "telephone": "",
                "userDesc": "",
                "isAdmin": 0,
                "qqId": "",
                "headPhoto": null,
                "accountId": "13795225919",
                "realName": "刘敏杰",
                "roleIds": "21",
                "extCode": "",
                "shdEnable": 0,
                "pwValidDate": 33009145985000,
                "createTime": 1476155306000,
                "entCode": "TJ",
                "weiboId": "",
                "wechatId": "",
                "cUserCode": "US000000137",
                "job": null,
                "status": 0,
                "lastUpdateTime": 1476940985000
            },
            {
                "superiorLeader": 34,
                "userCode": "US000000145",
                "orgId": 81,
                "orgCode": "021",
                "uUserCode": "US000000137",
                "id": 34,
                "email": "",
                "address": "",
                "isDelete": 0,
                "sex": 0,
                "mobile": "13761510281",
                "telephone": "",
                "userDesc": "",
                "isAdmin": 1,
                "qqId": "",
                "headPhoto": null,
                "accountId": "13761510281",
                "realName": "蒋晓芬",
                "roleIds": "19,36,36",
                "extCode": "",
                "shdEnable": 0,
                "pwValidDate": 33009145985000,
                "createTime": 1476155063000,
                "entCode": "TJ",
                "weiboId": "",
                "wechatId": "",
                "cUserCode": "US000000137",
                "job": null,
                "status": 1,
                "lastUpdateTime": 1479285672000
            },
            {
                "superiorLeader": null,
                "userCode": "US000000144",
                "orgId": 77,
                "orgCode": "019",
                "uUserCode": "US000000137",
                "id": 33,
                "email": "",
                "address": "",
                "isDelete": 0,
                "sex": 1,
                "mobile": "13675538495",
                "telephone": "",
                "userDesc": "",
                "isAdmin": 0,
                "qqId": "",
                "headPhoto": null,
                "accountId": "13675538495",
                "realName": "胡平",
                "roleIds": "10,36",
                "extCode": "",
                "shdEnable": 0,
                "pwValidDate": 33009145985000,
                "createTime": 1476151479000,
                "entCode": "TJ",
                "weiboId": "",
                "wechatId": "",
                "cUserCode": "US000000137",
                "job": null,
                "status": 0,
                "lastUpdateTime": 1476151479000
            },
            {
                "superiorLeader": 21,
                "userCode": "US000000143",
                "orgId": 77,
                "orgCode": "019",
                "uUserCode": "US000000143",
                "id": 32,
                "email": "",
                "address": "",
                "isDelete": 0,
                "sex": 1,
                "mobile": "15021417505",
                "telephone": "",
                "userDesc": "",
                "isAdmin": 1,
                "qqId": "",
                "headPhoto": null,
                "accountId": "15021417505",
                "realName": "戚瑞印",
                "roleIds": "26",
                "extCode": "",
                "shdEnable": 0,
                "pwValidDate": 33009145985000,
                "createTime": 1476151343000,
                "entCode": "TJ",
                "weiboId": "",
                "wechatId": "",
                "cUserCode": "US000000137",
                "job": null,
                "status": 1,
                "lastUpdateTime": 1478508243000
            },
            {
                "superiorLeader": 28,
                "userCode": "US000000142",
                "orgId": 77,
                "orgCode": "019",
                "uUserCode": "US000000137",
                "id": 31,
                "email": "",
                "address": "",
                "isDelete": 0,
                "sex": 1,
                "mobile": "15951982354",
                "telephone": "",
                "userDesc": "",
                "isAdmin": 1,
                "qqId": "",
                "headPhoto": null,
                "accountId": "15951982354",
                "realName": "陈亮",
                "roleIds": "26",
                "extCode": "",
                "shdEnable": 0,
                "pwValidDate": 33009145985000,
                "createTime": 1476151251000,
                "entCode": "TJ",
                "weiboId": "",
                "wechatId": "",
                "cUserCode": "US000000137",
                "job": null,
                "status": 1,
                "lastUpdateTime": 1476841816000
            },
            {
                "superiorLeader": 28,
                "userCode": "US000000141",
                "orgId": 77,
                "orgCode": "019",
                "uUserCode": "ME_0001",
                "id": 30,
                "email": "",
                "address": "",
                "isDelete": 0,
                "sex": 1,
                "mobile": "18721605134",
                "telephone": "",
                "userDesc": "",
                "isAdmin": 0,
                "qqId": "",
                "headPhoto": null,
                "accountId": "18721605134",
                "realName": "张硕",
                "roleIds": "28",
                "extCode": "",
                "shdEnable": 0,
                "pwValidDate": 33009145985000,
                "createTime": 1476151099000,
                "entCode": "TJ",
                "weiboId": "",
                "wechatId": "",
                "cUserCode": "US000000137",
                "job": null,
                "status": 0,
                "lastUpdateTime": 1476940965000
            },
            {
                "superiorLeader": 28,
                "userCode": "US000000140",
                "orgId": 77,
                "orgCode": "019",
                "uUserCode": "ME_0001",
                "id": 29,
                "email": "",
                "address": "",
                "isDelete": 0,
                "sex": 1,
                "mobile": "13816687619",
                "telephone": "",
                "userDesc": "",
                "isAdmin": 0,
                "qqId": "",
                "headPhoto": null,
                "accountId": "13816687619",
                "realName": "魏东潜",
                "roleIds": "28",
                "extCode": "",
                "shdEnable": 0,
                "pwValidDate": 33009145985000,
                "createTime": 1476070161000,
                "entCode": "TJ",
                "weiboId": "",
                "wechatId": "",
                "cUserCode": "US000000137",
                "job": null,
                "status": 0,
                "lastUpdateTime": 1476940942000
            },
            {
                "superiorLeader": null,
                "userCode": "US000000139",
                "orgId": 77,
                "orgCode": "019",
                "uUserCode": "ME_0001",
                "id": 28,
                "email": "",
                "address": "",
                "isDelete": 0,
                "sex": 1,
                "mobile": "13818006918",
                "telephone": "",
                "userDesc": "",
                "isAdmin": 1,
                "qqId": "",
                "headPhoto": null,
                "accountId": "13818006918",
                "realName": "樊华义",
                "roleIds": "18",
                "extCode": "",
                "shdEnable": 0,
                "pwValidDate": 33009145985000,
                "createTime": 1476070042000,
                "entCode": "TJ",
                "weiboId": "",
                "wechatId": "",
                "cUserCode": "US000000137",
                "job": null,
                "status": 1,
                "lastUpdateTime": 1476786147000
            },
            {
                "superiorLeader": 28,
                "userCode": "US000000138",
                "orgId": 77,
                "orgCode": "019",
                "uUserCode": "ME_0001",
                "id": 27,
                "email": "",
                "address": "",
                "isDelete": 0,
                "sex": 1,
                "mobile": "13262678761",
                "telephone": "",
                "userDesc": "",
                "isAdmin": 1,
                "qqId": "",
                "headPhoto": null,
                "accountId": "13262678761",
                "realName": "郭旺林",
                "roleIds": "26",
                "extCode": "",
                "shdEnable": 0,
                "pwValidDate": 33009145985000,
                "createTime": 1474879959000,
                "entCode": "TJ",
                "weiboId": "",
                "wechatId": "",
                "cUserCode": "US000000137",
                "job": null,
                "status": 1,
                "lastUpdateTime": 1477551555000
            },
            {
                "superiorLeader": 28,
                "userCode": "US000000137",
                "orgId": 77,
                "orgCode": "019",
                "uUserCode": "US000000137",
                "id": 26,
                "email": "",
                "address": "",
                "isDelete": 0,
                "sex": 0,
                "mobile": "18516261337",
                "telephone": "",
                "userDesc": "",
                "isAdmin": 1,
                "qqId": "",
                "headPhoto": null,
                "accountId": "18516261337",
                "realName": "朱志娟",
                "roleIds": "26",
                "extCode": "",
                "shdEnable": 0,
                "pwValidDate": 33009145985000,
                "createTime": 1470899527000,
                "entCode": "TJ",
                "weiboId": "",
                "wechatId": "",
                "cUserCode": "ME_0001",
                "job": null,
                "status": 1,
                "lastUpdateTime": 1479174032000
            },
            {
                "superiorLeader": null,
                "userCode": "US000000136",
                "orgId": 83,
                "orgCode": "023",
                "uUserCode": "ME_0001",
                "id": 25,
                "email": "",
                "address": "",
                "isDelete": 0,
                "sex": 1,
                "mobile": "15618396338",
                "telephone": "",
                "userDesc": "",
                "isAdmin": 0,
                "qqId": "",
                "headPhoto": null,
                "accountId": "15618396338",
                "realName": "李东辉",
                "roleIds": "20",
                "extCode": "",
                "shdEnable": 0,
                "pwValidDate": 33009137337000,
                "createTime": 1470123647000,
                "entCode": "TJ",
                "weiboId": "",
                "wechatId": "",
                "cUserCode": "ME_0001",
                "job": null,
                "status": 1,
                "lastUpdateTime": 1476772374000
            },
            {
                "superiorLeader": null,
                "userCode": "US000000134",
                "orgId": 81,
                "orgCode": "021",
                "uUserCode": "ME_0001",
                "id": 23,
                "email": "",
                "address": "",
                "isDelete": 0,
                "sex": 0,
                "mobile": "13564084821",
                "telephone": "",
                "userDesc": "",
                "isAdmin": 0,
                "qqId": "",
                "headPhoto": null,
                "accountId": "13564084821",
                "realName": "陆静慧",
                "roleIds": "1",
                "extCode": "",
                "shdEnable": 0,
                "pwValidDate": 33009137337000,
                "createTime": 1470117887000,
                "entCode": "TJ",
                "weiboId": "",
                "wechatId": "",
                "cUserCode": "ME_0001",
                "job": null,
                "status": 0,
                "lastUpdateTime": 1476786186000
            },
            {
                "superiorLeader": null,
                "userCode": "US000000132",
                "orgId": 84,
                "orgCode": "024",
                "uUserCode": "ME_0001",
                "id": 21,
                "email": "",
                "address": "",
                "isDelete": 0,
                "sex": 1,
                "mobile": "18321108865",
                "telephone": "",
                "userDesc": "",
                "isAdmin": 0,
                "qqId": "",
                "headPhoto": null,
                "accountId": "18321108865",
                "realName": "方炜",
                "roleIds": "28",
                "extCode": "",
                "shdEnable": 0,
                "pwValidDate": 33009137337000,
                "createTime": 1470116145000,
                "entCode": "TJ",
                "weiboId": "",
                "wechatId": "",
                "cUserCode": "ME_0001",
                "job": null,
                "status": 0,
                "lastUpdateTime": 1476940913000
            },
            {
                "superiorLeader": 35,
                "userCode": "US000000131",
                "orgId": 86,
                "orgCode": "024001",
                "uUserCode": "ME_0001",
                "id": 20,
                "email": "xiangpuxiang@ch-jht.com",
                "address": "",
                "isDelete": 0,
                "sex": 1,
                "mobile": "18616792351",
                "telephone": "",
                "userDesc": "",
                "isAdmin": 0,
                "qqId": "",
                "headPhoto": null,
                "accountId": "18616792351",
                "realName": "项普祥",
                "roleIds": "25",
                "extCode": "",
                "shdEnable": 0,
                "pwValidDate": 33009137337000,
                "createTime": 1470116112000,
                "entCode": "TJ",
                "weiboId": "",
                "wechatId": "",
                "cUserCode": "ME_0001",
                "job": null,
                "status": 0,
                "lastUpdateTime": 1476786281000
            },
            {
                "superiorLeader": 35,
                "userCode": "US000000130",
                "orgId": 86,
                "orgCode": "024001",
                "uUserCode": "ME_0001",
                "id": 19,
                "email": "",
                "address": "",
                "isDelete": 0,
                "sex": 0,
                "mobile": "18221737024",
                "telephone": "",
                "userDesc": "",
                "isAdmin": 0,
                "qqId": "",
                "headPhoto": null,
                "accountId": "18221737024",
                "realName": "张秀",
                "roleIds": "25",
                "extCode": "",
                "shdEnable": 0,
                "pwValidDate": 33009137337000,
                "createTime": 1470116044000,
                "entCode": "TJ",
                "weiboId": "",
                "wechatId": "",
                "cUserCode": "ME_0001",
                "job": null,
                "status": 0,
                "lastUpdateTime": 1476786290000
            },
            {
                "superiorLeader": 35,
                "userCode": "US000000129",
                "orgId": 86,
                "orgCode": "024001",
                "uUserCode": "ME_0001",
                "id": 18,
                "email": "",
                "address": "",
                "isDelete": 0,
                "sex": 1,
                "mobile": "18321768693",
                "telephone": "",
                "userDesc": "",
                "isAdmin": 0,
                "qqId": "",
                "headPhoto": null,
                "accountId": "18321768693",
                "realName": "高立宝",
                "roleIds": "25",
                "extCode": "",
                "shdEnable": 0,
                "pwValidDate": 33009137337000,
                "createTime": 1470116007000,
                "entCode": "TJ",
                "weiboId": "",
                "wechatId": "",
                "cUserCode": "ME_0001",
                "job": null,
                "status": 0,
                "lastUpdateTime": 1476786305000
            },
            {
                "superiorLeader": 17,
                "userCode": "US000000128",
                "orgId": 89,
                "orgCode": "014002",
                "uUserCode": "ME_0001",
                "id": 17,
                "email": "xujian@ch-jht.com",
                "address": "",
                "isDelete": 0,
                "sex": 1,
                "mobile": "18817430770",
                "telephone": "",
                "userDesc": "",
                "isAdmin": 0,
                "qqId": "",
                "headPhoto": null,
                "accountId": "18817430770",
                "realName": "徐建",
                "roleIds": "23",
                "extCode": "817",
                "shdEnable": 0,
                "pwValidDate": 33009137337000,
                "createTime": 1470115965000,
                "entCode": "TJ",
                "weiboId": "",
                "wechatId": "",
                "cUserCode": "ME_0001",
                "job": null,
                "status": 1,
                "lastUpdateTime": 1476786119000
            },
            {
                "superiorLeader": 16,
                "userCode": "US000000127",
                "orgId": 89,
                "orgCode": "014002",
                "uUserCode": "ME_0001",
                "id": 16,
                "email": "zhuyinchen@ch-jht.com",
                "address": "",
                "isDelete": 0,
                "sex": 1,
                "mobile": "13774357752",
                "telephone": "",
                "userDesc": "",
                "isAdmin": 0,
                "qqId": "",
                "headPhoto": null,
                "accountId": "13774357752",
                "realName": "朱寅晨",
                "roleIds": "27",
                "extCode": "",
                "shdEnable": 0,
                "pwValidDate": 33009137337000,
                "createTime": 1470115915000,
                "entCode": "TJ",
                "weiboId": "",
                "wechatId": "",
                "cUserCode": "ME_0001",
                "job": null,
                "status": 1,
                "lastUpdateTime": 1477449578000
            },
            {
                "superiorLeader": 1,
                "userCode": "US000000126",
                "orgId": 81,
                "orgCode": "021",
                "uUserCode": "US000000137",
                "id": 15,
                "email": "heshanshan@ch-jht.com",
                "address": "",
                "isDelete": 0,
                "sex": 0,
                "mobile": "15901913302",
                "telephone": "",
                "userDesc": "",
                "isAdmin": 0,
                "qqId": "",
                "headPhoto": null,
                "accountId": "15901913302",
                "realName": "何珊珊",
                "roleIds": "1",
                "extCode": "831",
                "shdEnable": 0,
                "pwValidDate": 33009137337000,
                "createTime": 1470115856000,
                "entCode": "TJ",
                "weiboId": "",
                "wechatId": "",
                "cUserCode": "ME_0001",
                "job": null,
                "status": 1,
                "lastUpdateTime": 1479285687000
            },
            {
                "superiorLeader": null,
                "userCode": "US000000154",
                "orgId": 70,
                "orgCode": "012",
                "uUserCode": "US000000137",
                "id": 203,
                "email": "",
                "address": "",
                "isDelete": 0,
                "sex": 0,
                "mobile": "18521031106",
                "telephone": "",
                "userDesc": "",
                "isAdmin": 0,
                "qqId": "",
                "headPhoto": null,
                "accountId": "18521031106",
                "realName": "张懿",
                "roleIds": "34",
                "extCode": "",
                "shdEnable": 0,
                "pwValidDate": 33009137337000,
                "createTime": 1470115856000,
                "entCode": "TJ",
                "weiboId": "",
                "wechatId": "",
                "cUserCode": "ME_0001",
                "job": "",
                "status": 1,
                "lastUpdateTime": 1479286728000
            },
            {
                "superiorLeader": null,
                "userCode": "ME_0001",
                "orgId": 0,
                "orgCode": "0",
                "uUserCode": "ME_0001",
                "id": 1,
                "email": "",
                "address": "",
                "isDelete": 0,
                "sex": 1,
                "mobile": "15000976418",
                "telephone": "",
                "userDesc": "",
                "isAdmin": 1,
                "qqId": "",
                "headPhoto": null,
                "accountId": "admin",
                "realName": "系统管理员",
                "roleIds": "26",
                "extCode": "800",
                "shdEnable": 0,
                "pwValidDate": 33009137337000,
                "createTime": 1401327600000,
                "entCode": "TJ",
                "weiboId": "",
                "wechatId": "",
                "cUserCode": "ME_0001",
                "job": null,
                "status": 1,
                "lastUpdateTime": 1478577505000
            }
        ],
        "logFileName": "G1_auth_A02005_13.log",
        "message": "操作成功",
        "uuid": "38FDF78617EF4F97BA399ABE0645DE6D",
        "status": 200,
        "errorParams": null
    };
    this.method('getData', function (orgCode) {
        M.$model=res.data;
    });





});

//唯一校验
model('unique',function () {
    var M = this,
        uniqueServer = this.server({
            serverType: 'api',
            url: 'realUnique'
        });

    this.method('valid', function (sendData,callbck) {
        uniqueServer.success(function (res) {
            callbck(M.$model=res);
        }).fail(function (msg) {
            callbck(false);
        }).send(sendData);
    })
});

//列表视图渲染
model('gridStruct',['$:@lib/custom/commApi/gridStruct'],function (gridStruct) {
    var M = this,
        gridServer = this.server({
            serverType: 'api',
            url: 'viewRenderConditions'
        });

    this.method('getData',function (fieldInfo) {
        var viewId=fieldInfo.selectViewId;
        gridServer.success(function (res) {
            M.$model=gridStruct(res,fieldInfo);
        }).fail(function () {
            M.$model=null;
        }).send({
            viewId:viewId
        })
    })

});